name=LC_SPI
version=1.0
author=jim lee
maintainer=SPI@leftcoast.biz
sentence=Automatic selection of pins that support hardware SPI.
paragraph=If the board you are using is on this list? Then your four shared SPI pin defines will now reflect your board's primare hardware supported pins. LC_CLK, LC_MISO, LC_MOSI, LC_DC  
category=Communications
url=https://github.com/leftCoast/LC_SPI
architectures=*
depends=LC_baseTools
dot_a_linkage=true